version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.11

    volumes:
      - ../..:/workspaces:cached
      
  plantuml:
    image: plantuml/plantuml-server:tomcat

#volumes:
#  postgres-data:
