version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.11

    volumes:
      - ../..:/workspaces:cached
    
    command: sleep infinity

  plantuml:
    image: plantuml/plantuml-server:tomcat